######################## default configuration ####################
baseURL = "https://demo.gethugothemes.com/hargo/site/"
languageCode = "en"
title = "Hargo | Hugo Ecommerce Site"
theme = "hargo-hugo"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/New_York"
# post pagination
paginate = 10 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 20 # see https://gohugo.io/content-management/excerpts/
# google analytics
googleAnalytics = "UA-123456-78" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = [
] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Products"
  URL = "products/"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog/"
  weight = 2

  [[menu.main]]
  name = "FAQ"
  URL = "faq/"
  weight = 3

  [[menu.main]]
  name = "Contact"
  URL = "contact/"
  weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Products"
  URL = "products/"
  weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "blog/"
  weight = 2

  [[menu.footer]]
  name = "FAQ"
  URL = "faq/"
  weight = 3

  [[menu.footer]]
  name = "Terms & Conditions"
  URL = "terms-conditions/"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "contact/"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalyticsID = "" # Your ID
# Contact Information
mobile = "0124857985320"
email = "demo@email.com"
location = "Dhaka, Bangladedsh"
# copyright
copyright = "| Copyright &copy; 2019 [Gethugothemes](https://gethugothemes.com) All Rights Reserved |"
# Snipcart Credentials
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
currencySymbol = "$"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "#"

  [[params.social]]
  icon = "ti-twitter-alt"
  link = "#"

  [[params.social]]
  icon = "ti-youtube"
  link = "#"

  [[params.social]]
  icon = "ti-instagram"
  link = "#"

  [[params.social]]
  icon = "ti-pinterest"
  link = "#"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io
